/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C
 * Generated (UTC): 2026-06-18T18:13:15Z
 * Log levels spec: spec/log_levels.json
 * Log levels spec version: 1
 */
#ifndef EWTS_LOG_LEVELS_H
#define EWTS_LOG_LEVELS_H

#ifdef __cplusplus
extern "C" {
#endif

static inline const char* ewts_log_level_name(int level) {
    switch (level) {
case 0: return "NOTSET";
case 10: return "DEBUG";
case 15: return "PERFORM";
case 20: return "INFO";
case 30: return "WARNING";
case 40: return "SEVERE";
case 50: return "FATAL";
case 60: return "STATUS";
        default: return "INFO";
    }
}

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // EWTS_LOG_LEVELS_H
