/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C
 * Generated (UTC): 2026-06-18T18:13:15Z
 * Module registry: spec/module_registry.yaml
 * Module registry version: 1
 */
#ifndef EWTS_MODULE_KEYS_H
#define EWTS_MODULE_KEYS_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    const char* key;
    const char* ewts_id;
    const char* description;
} ewts_module_entry;

extern const ewts_module_entry ewts_modules[];
extern const size_t ewts_modules_count;

// key -> ewts_id / description (returns NULL if not found)
const char* ewts_module_id_from_key(const char* key);
const char* ewts_description_from_key(const char* key);

// ewts_id -> keys / descriptions (duplicates supported)
// Returns number of matches. If out_* is NULL or max_* is 0, the function just counts.
size_t ewts_keys_from_module_id(const char* ewts_id, const char** out_keys, size_t max_keys);
size_t ewts_descriptions_from_module_id(const char* ewts_id, const char** out_descs, size_t max_descs);

// Convenience helpers: return first match in registry order, or NULL if none.
const char* ewts_first_key_from_module_id(const char* ewts_id);
const char* ewts_first_description_from_module_id(const char* ewts_id);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // EWTS_MODULE_KEYS_H
