/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C
 * Generated (UTC): 2026-06-18T18:13:15Z
 * Module registry: spec/module_registry.yaml
 * Module registry version: 1
 */

#ifndef EWTS_MODULE_CONSTANTS_H
#define EWTS_MODULE_CONSTANTS_H

/* Auto-generated constants for module keys and EWTS IDs. */

#define EWTS_KEY_CFE_S "cfe-s"
#define EWTS_ID_CFE_S "CFE"

#define EWTS_KEY_CFE_X "cfe-x"
#define EWTS_ID_CFE_X "CFE"

#define EWTS_KEY_CFE "cfe"
#define EWTS_ID_CFE "CFE"

#define EWTS_KEY_PET "pet"
#define EWTS_ID_PET "PET"

#define EWTS_KEY_TOPMODEL "topmodel"
#define EWTS_ID_TOPMODEL "TOPMODEL"

#endif  /* EWTS_MODULE_CONSTANTS_H */
