/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C
 * Generated (UTC): 2026-06-26T14:54:03Z
 * Payload status spec: spec/payload_status.json
 * Payload status spec version: 1
 * Payload status spec generated (UTC): 2026-06-26T00:00:00Z
 */
#ifndef PAYLOAD_STATUS_H
#define PAYLOAD_STATUS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Payload status string constants used in EWTS status payload messages. */
#define PAYLOAD_NULL "NULL"
#define PAYLOAD_INITTING "INITIALIZING"
#define PAYLOAD_INITTED "INITIALIZED"
#define PAYLOAD_STARTING "STARTING"
#define PAYLOAD_INPROG "IN_PROGRESS"
#define PAYLOAD_COMPLETE "COMPLETE"
#define PAYLOAD_ERROR "ERROR"

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // PAYLOAD_STATUS_H
