/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C++
 * Generated (UTC): 2026-06-18T18:13:15Z
 * Log levels spec: spec/log_levels.json
 * Log levels spec version: 1
 */
    #ifndef EWTS_LOG_LEVELS_HPP
    #define EWTS_LOG_LEVELS_HPP

    namespace ewts {
    inline const char* LogLevelName(int level) {
if (level == 0) return "NOTSET";
if (level == 10) return "DEBUG";
if (level == 15) return "PERFORM";
if (level == 20) return "INFO";
if (level == 30) return "WARNING";
if (level == 40) return "SEVERE";
if (level == 50) return "FATAL";
if (level == 60) return "STATUS";
        return "INFO";
    }
    }  // namespace ewts

    #endif  // EWTS_LOG_LEVELS_HPP
