/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C++
 * Generated (UTC): 2026-06-18T18:13:15Z
 * Module registry: spec/module_registry.yaml
 * Module registry version: 1
 */

#ifndef EWTS_MODULE_CONSTANTS_HPP
#define EWTS_MODULE_CONSTANTS_HPP

namespace ewts {
namespace modules {

inline constexpr const char* EWTS_KEY_NGEN = "ngen";
inline constexpr const char* EWTS_ID_NGEN  = "NGEN";

inline constexpr const char* EWTS_KEY_LASAM = "lasam";
inline constexpr const char* EWTS_ID_LASAM  = "LASAM";

inline constexpr const char* EWTS_KEY_SFT = "sft";
inline constexpr const char* EWTS_ID_SFT  = "SFT";

inline constexpr const char* EWTS_KEY_SMP = "smp";
inline constexpr const char* EWTS_ID_SMP  = "SMP";

inline constexpr const char* EWTS_KEY_UEB = "ueb";
inline constexpr const char* EWTS_ID_UEB  = "UEB_BMI";

}  // namespace modules
}  // namespace ewts

#endif  // EWTS_MODULE_CONSTANTS_HPP
