/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C++
 * Generated (UTC): 2026-06-26T14:54:03Z
 * Payload status spec: spec/payload_status.json
 * Payload status spec version: 1
 * Payload status spec generated (UTC): 2026-06-26T00:00:00Z
 */
#ifndef PAYLOAD_STATUS_HPP
#define PAYLOAD_STATUS_HPP

namespace ewts {

/* Payload status string constants used in EWTS status payload messages. */
inline constexpr const char* PAYLOAD_NULL = "NULL";
inline constexpr const char* PAYLOAD_INITTING = "INITIALIZING";
inline constexpr const char* PAYLOAD_INITTED = "INITIALIZED";
inline constexpr const char* PAYLOAD_STARTING = "STARTING";
inline constexpr const char* PAYLOAD_INPROG = "IN_PROGRESS";
inline constexpr const char* PAYLOAD_COMPLETE = "COMPLETE";
inline constexpr const char* PAYLOAD_ERROR = "ERROR";

}  // namespace ewts

#endif  // PAYLOAD_STATUS_HPP
