# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by tools/generate_language_constants.py
# Generated (UTC): 2026-06-18T18:13:15Z
# Log levels spec: spec/log_levels.json
# Log levels spec version: 1

from __future__ import annotations

LEVELS = {'NOTSET': 0, 'DEBUG': 10, 'PERFORM': 15, 'INFO': 20, 'WARNING': 30, 'SEVERE': 40, 'FATAL': 50, 'STATUS': 60}

def log_level_name(level: int) -> str:
    for name, val in LEVELS.items():
        if val == level:
            return name
    return "INFO"

def parse_log_level(level: str | int | None, default: int = LEVELS["INFO"]) -> int:
    """
    Normalize a log level into an EWTS integer level.

    Accepts:
      - int: returned as-is
      - str: case-insensitive EWTS level name
      - None: returns default

    NOTE:
      - No aliases are supported.
    """
    if level is None:
        return default

    if isinstance(level, int):
        return level

    if isinstance(level, str):
        return LEVELS.get(level.strip().upper(), default)

    return default
