# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by tools/generate_language_constants.py
# Generated (UTC): 2026-06-18T18:13:15Z
# Module registry: spec/module_registry.yaml
# Module registry version: 1

from __future__ import annotations
from enum import Enum

class ModuleKey(str, Enum):
    FORCING = "forcing"
    LSTM = "lstm"
    TOPOFLOW_GLACIER = "topoflow-glacier"
    T_ROUTE = "t-route"
    MSW_MGR = "msw-mgr"
    CAL_MGR = "cal-mgr"
    EVAL_MGR = "eval-mgr"
    FCST_MGR = "fcst-mgr"
    RTE = "rte"
    ASSIM_ENGINE = "assim-engine"


FORCING_KEY = "forcing"
LSTM_KEY = "lstm"
TOPOFLOW_GLACIER_KEY = "topoflow-glacier"
T_ROUTE_KEY = "t-route"
MSW_MGR_KEY = "msw-mgr"
CAL_MGR_KEY = "cal-mgr"
EVAL_MGR_KEY = "eval-mgr"
FCST_MGR_KEY = "fcst-mgr"
RTE_KEY = "rte"
ASSIM_ENGINE_KEY = "assim-engine"

FORCING_ID = "FORCING"
LSTM_ID = "LSTM"
TOPOFLOW_GLACIER_ID = "TFGLACR"
T_ROUTE_ID = "TROUTE"
MSW_MGR_ID = "MSWMGR"
CAL_MGR_ID = "CALMGR"
EVAL_MGR_ID = "EVALMGR"
FCST_MGR_ID = "FCSTMGR"
RTE_ID = "RTE"
ASSIM_ENGINE_ID = "ASSIM"

__all__ = [
    "ModuleKey",
    "FORCING_KEY", "FORCING_ID",
    "LSTM_KEY", "LSTM_ID",
    "TOPOFLOW_GLACIER_KEY", "TOPOFLOW_GLACIER_ID",
    "T_ROUTE_KEY", "T_ROUTE_ID",
    "MSW_MGR_KEY", "MSW_MGR_ID",
    "CAL_MGR_KEY", "CAL_MGR_ID",
    "EVAL_MGR_KEY", "EVAL_MGR_ID",
    "FCST_MGR_KEY", "FCST_MGR_ID",
    "RTE_KEY", "RTE_ID",
    "ASSIM_ENGINE_KEY", "ASSIM_ENGINE_ID",
]
