! AUTO-GENERATED FILE. DO NOT EDIT.
! Generated by tools/generate_language_constants.py
! Generated (UTC): 2026-06-18T18:13:15Z
! Log levels spec: spec/log_levels.json
! Log levels spec version: 1

module ewts_log_levels
  implicit none
contains
  pure function ewts_log_level_name(level) result(name)
    integer, intent(in) :: level
    character(len=16) :: name
    select case (level)
            case (0)
              name = "NOTSET"
            case (10)
              name = "DEBUG"
            case (15)
              name = "PERFORM"
            case (20)
              name = "INFO"
            case (30)
              name = "WARNING"
            case (40)
              name = "SEVERE"
            case (50)
              name = "FATAL"
            case (60)
              name = "STATUS"
    case default
      name = "INFO"
    end select
  end function ewts_log_level_name
end module ewts_log_levels
