! AUTO-GENERATED FILE. DO NOT EDIT.
! Generated by tools/generate_language_constants.py
! Generated (UTC): 2026-06-18T18:13:15Z
! Module registry: spec/module_registry.yaml
! Module registry version: 1

module ewts_module_keys
  implicit none

  integer, parameter :: EWTS_MODULE_COUNT = 5
  integer, parameter :: EWTS_KEY_LEN = 16
  integer, parameter :: EWTS_ID_LEN = 7
  integer, parameter :: EWTS_DESC_LEN = 71

  character(len=EWTS_KEY_LEN), parameter :: EWTS_KEYS(EWTS_MODULE_COUNT) = &
    [character(len=EWTS_KEY_LEN) :: &
      "noah-owp-modular", "sac-sma", "snow-17", "schism", "sfincs" &
    ]

  character(len=EWTS_ID_LEN), parameter :: EWTS_IDS(EWTS_MODULE_COUNT) = &
    [character(len=EWTS_ID_LEN) :: &
      "NOAHOWP", "SACSMA", "SNOW17", "SCHISM", "SFINCS" &
    ]

  character(len=EWTS_DESC_LEN), parameter :: EWTS_DESCS(EWTS_MODULE_COUNT) = &
    [character(len=EWTS_DESC_LEN) :: &
      "Noah OWP Land Surface Model", &
      "Sacramento Soil Moisture Accounting Model", &
      "Snow Cccumulation and Melt Model", &
      "Semi-implicit Cross-scale Hydroscience Integrated System Model (SCHISM)", &
      "Super-fast modelling of dynamic compound flooding in Coastal Systems" &
    ]

contains

  pure function ewts_id_from_key(key) result(ewts_id)
    character(len=*), intent(in) :: key
    character(len=EWTS_ID_LEN) :: ewts_id
    integer :: i
    ewts_id = ""
    do i = 1, EWTS_MODULE_COUNT
      if (trim(EWTS_KEYS(i)) == trim(key)) then
        ewts_id = EWTS_IDS(i)
        return
      end if
    end do
  end function ewts_id_from_key

  pure function ewts_description_from_key(key) result(desc)
    character(len=*), intent(in) :: key
    character(len=EWTS_DESC_LEN) :: desc
    integer :: i
    desc = ""
    do i = 1, EWTS_MODULE_COUNT
      if (trim(EWTS_KEYS(i)) == trim(key)) then
        desc = EWTS_DESCS(i)
        return
      end if
    end do
  end function ewts_description_from_key

  subroutine ewts_keys_from_id(ewts_id, out_keys, n)
    character(len=*), intent(in) :: ewts_id
    character(len=*), dimension(:), intent(out) :: out_keys
    integer, intent(out) :: n
    integer :: i, k
    n = 0
    k = 0
    do i = 1, EWTS_MODULE_COUNT
      if (trim(EWTS_IDS(i)) == trim(ewts_id)) then
        n = n + 1
        if (k < size(out_keys)) then
          k = k + 1
          out_keys(k) = trim(EWTS_KEYS(i))
        end if
      end if
    end do
  end subroutine ewts_keys_from_id

  subroutine ewts_descs_from_id(ewts_id, out_descs, n)
    character(len=*), intent(in) :: ewts_id
    character(len=*), dimension(:), intent(out) :: out_descs
    integer, intent(out) :: n
    integer :: i, k
    n = 0
    k = 0
    do i = 1, EWTS_MODULE_COUNT
      if (trim(EWTS_IDS(i)) == trim(ewts_id)) then
        n = n + 1
        if (k < size(out_descs)) then
          k = k + 1
          out_descs(k) = trim(EWTS_DESCS(i))
        end if
      end if
    end do
  end subroutine ewts_descs_from_id

end module ewts_module_keys
