! AUTO-GENERATED FILE. DO NOT EDIT.
! Generated by tools/generate_language_constants.py
! Generated (UTC): 2026-06-26T14:54:03Z
! Payload status spec: spec/payload_status.json
! Payload status spec version: 1
! Payload status spec generated (UTC): 2026-06-26T00:00:00Z

module ewts_payload_status
  implicit none

  integer, parameter :: PAYLOAD_STATUS_LEN = 12

  character(len=*), parameter :: PAYLOAD_NULL = "NULL"
  character(len=*), parameter :: PAYLOAD_INITTING = "INITIALIZING"
  character(len=*), parameter :: PAYLOAD_INITTED = "INITIALIZED"
  character(len=*), parameter :: PAYLOAD_STARTING = "STARTING"
  character(len=*), parameter :: PAYLOAD_INPROG = "IN_PROGRESS"
  character(len=*), parameter :: PAYLOAD_COMPLETE = "COMPLETE"
  character(len=*), parameter :: PAYLOAD_ERROR = "ERROR"

end module ewts_payload_status
