#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import textwrap
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

try:
    import yaml  # PyYAML
except ImportError as e:
    raise SystemExit("Missing dependency: pyyaml. Install with: pip install pyyaml") from e


# One timestamp for all generated outputs in a single run
GEN_UTC = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

GENERATED_FILES: List[Path] = []
EWTS_ID_WIDTH = 8

# These are populated from the log-levels spec via _load_log_levels()
LEVELS: Dict[str, int] = {
    "NOTSET": 0,
    "DEBUG": 10,
    "PERFORM": 15,
    "INFO": 20,
    "WARNING": 30,
    "ERROR": 40,
    "SEVERE": 40,
    "FATAL": 50,
    "CRITICAL": 50,
}
DEFAULT_LEVEL_NAME = "INFO"

# These are populated from the payload-status spec via _load_payload_statuses()
PAYLOAD_STATUSES: Dict[str, str] = {
    "NULL": "NULL",
    "INITTING": "INITIALIZING",
    "INITTED": "INITIALIZED",
    "STARTING": "STARTING",
    "INPROG": "IN_PROGRESS",
    "COMPLETE": "COMPLETE",
    "ERROR": "ERROR",
}
DEFAULT_PAYLOAD_STATUS_NAME = "ERROR"


@dataclass(frozen=True)
class Module:
    key: str
    ewts_id: str
    language: str
    description: str = ""


# ----------------------- Module key constants helpers -----------------------

def _ident_from_key(key: str) -> str:
    """Convert a registry key like 't-route' into an identifier like 'T_ROUTE'."""
    s = key.strip().upper()
    s = re.sub(r"[^A-Z0-9]+", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    if not s:
        s = "MODULE"
    if s[0].isdigit():
        s = "M_" + s
    return s

def _infer_repo_root_from_script(script_path: Path) -> Path:
    # If this script lives at <repo>/tools/generate_language_constants.py
    # then repo root is the parent of the tools dir.
    return script_path.resolve().parent.parent


def _ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _write_text(path: Path, content: str) -> None:
    _ensure_parent(path)
    path.write_text(content, encoding="utf-8")
    GENERATED_FILES.append(path)


def _rel(repo_root: Path, p: Path) -> str:
    try:
        return p.resolve().relative_to(repo_root.resolve()).as_posix()
    except Exception:
        return p.as_posix()


def _c_block_banner(
    lang: str,
    *,
    generated_utc: str,
    registry_meta: Optional[dict] = None,
    levels_meta: Optional[dict] = None,
    payload_meta: Optional[dict] = None,
) -> str:
    # Block comment is valid in both C and C++
    lines = [
        "/* AUTO-GENERATED FILE. DO NOT EDIT.",
        " * Generated by tools/generate_language_constants.py",
        f" * Language: {lang}",
        f" * Generated (UTC): {generated_utc}",
    ]
    if registry_meta:
        lines.append(f" * Module registry: {registry_meta.get('spec_path', 'unknown')}")
        lines.append(f" * Module registry version: {registry_meta.get('spec_version', 'unknown')}")
        if registry_meta.get("spec_generated_utc"):
            lines.append(
                f" * Module registry generated (UTC): {registry_meta.get('spec_generated_utc')}"
            )
    if levels_meta:
        lines.append(f" * Log levels spec: {levels_meta.get('spec_path', 'unknown')}")
        lines.append(f" * Log levels spec version: {levels_meta.get('spec_version', 'unknown')}")
        if levels_meta.get("spec_generated_utc"):
            lines.append(
                f" * Log levels spec generated (UTC): {levels_meta.get('spec_generated_utc')}"
            )
    if payload_meta:
        lines.append(f" * Payload status spec: {payload_meta.get('spec_path', 'unknown')}")
        lines.append(f" * Payload status spec version: {payload_meta.get('spec_version', 'unknown')}")
        if payload_meta.get("spec_generated_utc"):
            lines.append(
                f" * Payload status spec generated (UTC): {payload_meta.get('spec_generated_utc')}"
            )
    lines.append(" */\n")
    return "\n".join(lines)


def _py_banner(
    *,
    generated_utc: str,
    registry_meta: Optional[dict] = None,
    levels_meta: Optional[dict] = None,
    payload_meta: Optional[dict] = None,
) -> str:
    lines = [
        "# AUTO-GENERATED FILE. DO NOT EDIT.",
        "# Generated by tools/generate_language_constants.py",
        f"# Generated (UTC): {generated_utc}",
    ]
    if registry_meta:
        lines.append(f"# Module registry: {registry_meta.get('spec_path', 'unknown')}")
        lines.append(f"# Module registry version: {registry_meta.get('spec_version', 'unknown')}")
        if registry_meta.get("spec_generated_utc"):
            lines.append(
                f"# Module registry generated (UTC): {registry_meta.get('spec_generated_utc')}"
            )
    if levels_meta:
        lines.append(f"# Log levels spec: {levels_meta.get('spec_path', 'unknown')}")
        lines.append(f"# Log levels spec version: {levels_meta.get('spec_version', 'unknown')}")
        if levels_meta.get("spec_generated_utc"):
            lines.append(
                f"# Log levels spec generated (UTC): {levels_meta.get('spec_generated_utc')}"
            )
    if payload_meta:
        lines.append(f"# Payload status spec: {payload_meta.get('spec_path', 'unknown')}")
        lines.append(f"# Payload status spec version: {payload_meta.get('spec_version', 'unknown')}")
        if payload_meta.get("spec_generated_utc"):
            lines.append(
                f"# Payload status spec generated (UTC): {payload_meta.get('spec_generated_utc')}"
            )
    return "\n".join(lines) + "\n\n"


def _f_banner(
    *,
    generated_utc: str,
    registry_meta: Optional[dict] = None,
    levels_meta: Optional[dict] = None,
    payload_meta: Optional[dict] = None,
) -> str:
    lines = [
        "! AUTO-GENERATED FILE. DO NOT EDIT.",
        "! Generated by tools/generate_language_constants.py",
        f"! Generated (UTC): {generated_utc}",
    ]
    if registry_meta:
        lines.append(f"! Module registry: {registry_meta.get('spec_path', 'unknown')}")
        lines.append(f"! Module registry version: {registry_meta.get('spec_version', 'unknown')}")
        if registry_meta.get("spec_generated_utc"):
            lines.append(
                f"! Module registry generated (UTC): {registry_meta.get('spec_generated_utc')}"
            )
    if levels_meta:
        lines.append(f"! Log levels spec: {levels_meta.get('spec_path', 'unknown')}")
        lines.append(f"! Log levels spec version: {levels_meta.get('spec_version', 'unknown')}")
        if levels_meta.get("spec_generated_utc"):
            lines.append(
                f"! Log levels spec generated (UTC): {levels_meta.get('spec_generated_utc')}"
            )
    if payload_meta:
        lines.append(f"! Payload status spec: {payload_meta.get('spec_path', 'unknown')}")
        lines.append(f"! Payload status spec version: {payload_meta.get('spec_version', 'unknown')}")
        if payload_meta.get("spec_generated_utc"):
            lines.append(
                f"! Payload status spec generated (UTC): {payload_meta.get('spec_generated_utc')}"
            )
    return "\n".join(lines) + "\n\n"


def _load_registry(registry_path: Path) -> List[Module]:
    data = yaml.safe_load(registry_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or "modules" not in data or not isinstance(data["modules"], list):
        raise SystemExit("Registry must be a YAML mapping with a top-level 'modules' list.")

    modules: List[Module] = []
    for i, raw in enumerate(data["modules"]):
        if not isinstance(raw, dict):
            raise SystemExit(f"Registry entry #{i} must be a mapping.")
        key = str(raw.get("key", "")).strip()
        ewts_id = str(raw.get("ewts_id", "")).strip()
        language = str(raw.get("language", "")).strip().lower()
        desc = str(raw.get("description", "")).strip()

        if not key:
            raise SystemExit(f"Registry entry #{i} has an empty 'key'.")
        if not ewts_id:
            raise SystemExit(f"Registry entry #{i} has an empty 'ewts_id'.")
        if not language:
            raise SystemExit(f"Registry entry #{i} has an empty 'language'.")
        if language not in {"c", "cpp", "fortran", "python"}:
            raise SystemExit(
                f"Registry entry #{i} has unsupported language '{language}'. "
                "Expected one of: c, cpp, fortran, python."
            )
        if len(ewts_id) > EWTS_ID_WIDTH:
            raise SystemExit(f"Registry entry #{i} ewts_id '{ewts_id}' exceeds {EWTS_ID_WIDTH} chars.")
        if ewts_id.upper() != ewts_id:
            raise SystemExit(f"Registry entry #{i} ewts_id '{ewts_id}' must be uppercase.")
        modules.append(Module(key=key, ewts_id=ewts_id, language=language, description=desc))
    return modules


def _modules_for_language(modules: List[Module], language: str) -> List[Module]:
    return [m for m in modules if m.language == language]


def _registry_meta(repo_root: Path, registry_path: Path) -> dict:
    data = yaml.safe_load(registry_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit("Registry must be a YAML mapping at the top level.")
    version = data.get("version")
    generated_utc = data.get("generated_utc") or data.get("generatedUTC")  # tolerate variants

    if version is not None and not isinstance(version, (int, str)):
        raise SystemExit("Registry 'version' must be an int or string when present.")
    if generated_utc is not None and not isinstance(generated_utc, str):
        raise SystemExit("Registry 'generated_utc' must be a string when present.")

    return {
        "spec_path": _rel(repo_root, registry_path),
        "spec_version": str(version) if version is not None else "unknown",
        "spec_generated_utc": generated_utc,
    }


def _validate_registry(modules: List[Module]) -> None:
    # Keys must be unique
    seen: Dict[str, int] = {}
    for i, m in enumerate(modules):
        if m.key in seen:
            j = seen[m.key]
            raise SystemExit(f"Duplicate module key '{m.key}' at entries {j} and {i}. Keys must be unique.")
        seen[m.key] = i
    # NOTE: ewts_id values are allowed to be duplicated (e.g., aliases like CFE)


def _load_log_levels(log_levels_path: Path) -> dict:
    """Load log levels from JSON into global LEVELS/DEFAULT_LEVEL_NAME.

    Expected shape (minimal):
      {"levels": {"DEBUG": 10, "INFO": 20, ...}}

    Extra keys are allowed and used for provenance (e.g., version, generated_utc, canonical_names).
    Returns metadata for banners.
    """
    global LEVELS, DEFAULT_LEVEL_NAME

    data = json.loads(log_levels_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit("log_levels.json must be a JSON object at the top level.")

    levels = data.get("levels")
    if not isinstance(levels, dict) or not levels:
        raise SystemExit("log_levels.json must contain a non-empty 'levels' object.")

    parsed: Dict[str, int] = {}
    for name, val in levels.items():
        if not isinstance(name, str) or not name.strip():
            raise SystemExit("log_levels.json 'levels' keys must be non-empty strings.")
        if not isinstance(val, int):
            raise SystemExit(f"log_levels.json level '{name}' must be an integer, got {type(val).__name__}.")
        parsed[name.strip()] = val

    # Deterministic: preserve JSON order for Python dicts (3.7+)
    LEVELS = parsed

    # Stable default selection
    if "INFO" in LEVELS:
        DEFAULT_LEVEL_NAME = "INFO"
    elif DEFAULT_LEVEL_NAME in LEVELS:
        pass
    else:
        min_val = min(LEVELS.values())
        for n, v in LEVELS.items():
            if v == min_val:
                DEFAULT_LEVEL_NAME = n
                break

    version = data.get("version")
    generated_utc = data.get("generated_utc")

    if version is not None and not isinstance(version, int):
        raise SystemExit(f"log_levels.json 'version' must be an integer when present, got {type(version).__name__}.")
    if generated_utc is not None and not isinstance(generated_utc, str):
        raise SystemExit(
            f"log_levels.json 'generated_utc' must be a string when present, got {type(generated_utc).__name__}."
        )

    return {
        "spec_path": log_levels_path.as_posix(),  # caller will rewrite to repo-relative
        "spec_version": str(version) if version is not None else "unknown",
        "spec_generated_utc": generated_utc,
    }



def _load_payload_statuses(payload_status_path: Path) -> dict:
    """Load payload statuses from JSON into global PAYLOAD_STATUSES.

    Expected shape (minimal):
      {"statuses": {"NULL": "NULL", "INITTING": "INITIALIZING", "COMPLETE": "COMPLETE", ...}}

    Extra keys are allowed and used for provenance (e.g., version, generated_utc).
    Returns metadata for banners.
    """
    global PAYLOAD_STATUSES, DEFAULT_PAYLOAD_STATUS_NAME

    data = json.loads(payload_status_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit("payload_status.json must be a JSON object at the top level.")

    statuses = data.get("statuses")
    if not isinstance(statuses, dict) or not statuses:
        raise SystemExit("payload_status.json must contain a non-empty 'statuses' object.")

    parsed: Dict[str, str] = {}
    for name, val in statuses.items():
        if not isinstance(name, str) or not name.strip():
            raise SystemExit("payload_status.json 'statuses' keys must be non-empty strings.")
        if not isinstance(val, str) or not val.strip():
            raise SystemExit(
                f"payload_status.json status '{name}' must be a non-empty string, got {type(val).__name__}."
            )
        key = name.strip().upper()
        value = val.strip().upper()
        parsed[key] = value

    PAYLOAD_STATUSES = parsed

    if "ERROR" in PAYLOAD_STATUSES:
        DEFAULT_PAYLOAD_STATUS_NAME = "ERROR"
    else:
        DEFAULT_PAYLOAD_STATUS_NAME = next(iter(PAYLOAD_STATUSES))

    version = data.get("version")
    generated_utc = data.get("generated_utc")

    if version is not None and not isinstance(version, int):
        raise SystemExit(
            f"payload_status.json 'version' must be an integer when present, got {type(version).__name__}."
        )
    if generated_utc is not None and not isinstance(generated_utc, str):
        raise SystemExit(
            f"payload_status.json 'generated_utc' must be a string when present, got {type(generated_utc).__name__}."
        )

    return {
        "spec_path": payload_status_path.as_posix(),  # caller will rewrite to repo-relative
        "spec_version": str(version) if version is not None else "unknown",
        "spec_generated_utc": generated_utc,
    }

# ----------------------- Generators -----------------------


def _generate_c_module_constants(modules: List[Module], out_h: Path, *, repo_root: Path, registry_meta: dict) -> None:
    """Generate C macros for module keys and ids to avoid typos in call sites."""
    lines = [
        _c_block_banner("C", generated_utc=GEN_UTC, registry_meta=registry_meta),
        "#ifndef EWTS_MODULE_CONSTANTS_H",
        "#define EWTS_MODULE_CONSTANTS_H",
        "",
        "/* Auto-generated constants for module keys and EWTS IDs. */",
        "",
    ]
    for m in modules:
        ident = _ident_from_key(m.key)
        lines.append(f'#define EWTS_KEY_{ident} "{m.key}"')
        lines.append(f'#define EWTS_ID_{ident} "{m.ewts_id}"')
        lines.append("")
    lines.append("#endif  /* EWTS_MODULE_CONSTANTS_H */\n")
    _write_text(out_h, "\n".join(lines))


def _generate_cpp_module_constants(modules: List[Module], out_hpp: Path, *, registry_meta: dict) -> None:
    """Generate C++ constexpr strings for module keys and ids."""
    lines = [
        _c_block_banner("C++", generated_utc=GEN_UTC, registry_meta=registry_meta),
        "#ifndef EWTS_MODULE_CONSTANTS_HPP",
        "#define EWTS_MODULE_CONSTANTS_HPP",
        "",
        "namespace ewts {",
        "namespace modules {",
        "",
    ]
    for m in modules:
        ident = _ident_from_key(m.key)
        lines.append(f'inline constexpr const char* EWTS_KEY_{ident} = "{m.key}";')
        lines.append(f'inline constexpr const char* EWTS_ID_{ident}  = "{m.ewts_id}";')
        lines.append("")
    lines.extend([
        "}  // namespace modules",
        "}  // namespace ewts",
        "",
        "#endif  // EWTS_MODULE_CONSTANTS_HPP\n",
    ])
    _write_text(out_hpp, "\n".join(lines))


def _generate_ngen_module_constants(modules: List[Module], out_hpp: Path, *, registry_meta: dict) -> None:
    """Generate aggregate C++ constants for the ngen integration without affecting runtime headers."""
    lines = [
        _c_block_banner("C++", generated_utc=GEN_UTC, registry_meta=registry_meta),
        "#ifndef EWTS_NGEN_MODULE_CONSTANTS_HPP",
        "#define EWTS_NGEN_MODULE_CONSTANTS_HPP",
        "",
        "namespace ewts_ngen {",
        "namespace modules {",
        "",
    ]
    for m in modules:
        ident = _ident_from_key(m.key)
        lines.append(f'inline constexpr const char* EWTS_KEY_{ident} = "{m.key}";')
        lines.append(f'inline constexpr const char* EWTS_ID_{ident}  = "{m.ewts_id}";')
        lines.append("")
    lines.extend([
        "}  // namespace modules",
        "}  // namespace ewts_ngen",
        "",
        "#endif  // EWTS_NGEN_MODULE_CONSTANTS_HPP\n",
    ])
    _write_text(out_hpp, "\n".join(lines))




def _generate_ngen_module_keys(modules: List[Module], out_hpp: Path, *, registry_meta: dict) -> None:
    """Generate aggregate C++ module key helpers for the ngen integration without affecting runtime headers."""
    entries = []
    for m in modules:
        desc = m.description.replace("\\", "\\\\").replace('"', '\\"')
        entries.append(f'    {{"{m.key}", "{m.ewts_id}", "{desc}"}}')
    entries_block = ",\n".join(entries)

    content = _c_block_banner(
        "C++",
        generated_utc=GEN_UTC,
        registry_meta=registry_meta,
    ) + textwrap.dedent(f"""\
        #ifndef EWTS_NGEN_MODULE_KEYS_HPP
        #define EWTS_NGEN_MODULE_KEYS_HPP

        #include <cstddef>
        #include <cstring>
        #include <vector>

        namespace ewts_ngen {{
        struct ModuleEntry {{
            const char* key;
            const char* ewts_id;
            const char* description;
        }};

        static const ModuleEntry kModules[] = {{
{entries_block}
        }};

        static const std::size_t kModulesCount = sizeof(kModules) / sizeof(kModules[0]);

        inline const char* EwtsIdFromKey(const char* key) {{
            if (!key) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].key, key) == 0) return kModules[i].ewts_id;
            }}
            return nullptr;
        }}

        inline const char* DescriptionFromKey(const char* key) {{
            if (!key) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].key, key) == 0) return kModules[i].description;
            }}
            return nullptr;
        }}

        inline std::vector<const char*> KeysFromEwtsId(const char* ewts_id) {{
            std::vector<const char*> out;
            if (!ewts_id) return out;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) out.push_back(kModules[i].key);
            }}
            return out;
        }}

        inline std::vector<const char*> DescriptionsFromEwtsId(const char* ewts_id) {{
            std::vector<const char*> out;
            if (!ewts_id) return out;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) out.push_back(kModules[i].description);
            }}
            return out;
        }}

        inline const char* FirstKeyFromEwtsId(const char* ewts_id) {{
            if (!ewts_id) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) return kModules[i].key;
            }}
            return nullptr;
        }}

        inline const char* FirstDescriptionFromEwtsId(const char* ewts_id) {{
            if (!ewts_id) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) return kModules[i].description;
            }}
            return nullptr;
        }}

        }}  // namespace ewts_ngen

        #endif  // EWTS_NGEN_MODULE_KEYS_HPP
    """)
    _write_text(out_hpp, content)


def _generate_fortran_module_constants(modules: List[Module], out_f90: Path, *, registry_meta: dict) -> None:
    """Generate Fortran parameters for module keys and ids."""
    content = _f_banner(generated_utc=GEN_UTC, registry_meta=registry_meta)
    content += "module ewts_module_constants\n"
    content += "  implicit none\n\n"
    for m in modules:
        ident = _ident_from_key(m.key)
        content += f'  character(len=*), parameter :: EWTS_KEY_{ident} = "{m.key}"\n'
        content += f'  character(len=*), parameter :: EWTS_ID_{ident}  = "{m.ewts_id}"\n\n'
    content += "end module ewts_module_constants\n"
    _write_text(out_f90, content)


def _generate_python_module_constants(modules: List[Module], out_py: Path, *, registry_meta: dict) -> None:
    """Generate Python constants + Enum for module keys/ids to avoid typos."""
    enum_items = []
    for m in modules:
        ident = _ident_from_key(m.key)
        enum_items.append((ident, m.key, m.ewts_id))

    lines = [
        _py_banner(generated_utc=GEN_UTC, registry_meta=registry_meta),
        "from __future__ import annotations\n",
        "from enum import Enum\n\n",
        "class ModuleKey(str, Enum):\n",
    ]
    for name, key, _ in enum_items:
        lines.append(f'    {name} = "{key}"\n')
    lines.append("\n\n")
    for name, key, _ in enum_items:
        lines.append(f'{name}_KEY = "{key}"\n')
    lines.append("\n")
    for name, _, ewts_id in enum_items:
        lines.append(f'{name}_ID = "{ewts_id}"\n')

    lines.append("\n__all__ = [\n    \"ModuleKey\",\n")
    for name, _, _ in enum_items:
        lines.append(f'    "{name}_KEY", "{name}_ID",\n')
    lines.append("]\n")

    _write_text(out_py, "".join(lines))

def _generate_c_module_keys(modules: List[Module], out_h: Path, *, repo_root: Path, registry_meta: dict) -> None:
    entries = []
    for m in modules:
        desc = m.description.replace('"', '\\"')
        entries.append(f'    {{"{m.key}", "{m.ewts_id}", "{desc}"}}')

    content = _c_block_banner(
        "C",
        generated_utc=GEN_UTC,
        registry_meta=registry_meta,
    ) + textwrap.dedent("""\
        #ifndef EWTS_MODULE_KEYS_H
        #define EWTS_MODULE_KEYS_H

        #include <stddef.h>

        #ifdef __cplusplus
        extern "C" {
        #endif

        typedef struct {
            const char* key;
            const char* ewts_id;
            const char* description;
        } ewts_module_entry;

        extern const ewts_module_entry ewts_modules[];
        extern const size_t ewts_modules_count;

        // key -> ewts_id / description (returns NULL if not found)
        const char* ewts_module_id_from_key(const char* key);
        const char* ewts_description_from_key(const char* key);

        // ewts_id -> keys / descriptions (duplicates supported)
        // Returns number of matches. If out_* is NULL or max_* is 0, the function just counts.
        size_t ewts_keys_from_module_id(const char* ewts_id, const char** out_keys, size_t max_keys);
        size_t ewts_descriptions_from_module_id(const char* ewts_id, const char** out_descs, size_t max_descs);

        // Convenience helpers: return first match in registry order, or NULL if none.
        const char* ewts_first_key_from_module_id(const char* ewts_id);
        const char* ewts_first_description_from_module_id(const char* ewts_id);

        #ifdef __cplusplus
        }  // extern "C"
        #endif

        #endif  // EWTS_MODULE_KEYS_H
    """)

    entries_block = ",\n".join(entries)
    impl = _c_block_banner(
        "C",
        generated_utc=GEN_UTC,
        registry_meta=registry_meta,
    ) + textwrap.dedent(f"""\
        #include "ewts/module_keys.h"
        #include <string.h>

        const ewts_module_entry ewts_modules[] = {{
        {entries_block}
        }};

        const size_t ewts_modules_count = sizeof(ewts_modules) / sizeof(ewts_modules[0]);

        const char* ewts_module_id_from_key(const char* key) {{
            if (!key) return NULL;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].key, key) == 0) {{
                    return ewts_modules[i].ewts_id;
                }}
            }}
            return NULL;
        }}

        const char* ewts_description_from_key(const char* key) {{
            if (!key) return NULL;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].key, key) == 0) {{
                    return ewts_modules[i].description;
                }}
            }}
            return NULL;
        }}

        size_t ewts_keys_from_module_id(const char* ewts_id, const char** out_keys, size_t max_keys) {{
            if (!ewts_id) return 0;
            size_t n = 0;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {{
                    if (out_keys && n < max_keys) {{
                        out_keys[n] = ewts_modules[i].key;
                    }}
                    ++n;
                }}
            }}
            return n;
        }}

        size_t ewts_descriptions_from_module_id(const char* ewts_id, const char** out_descs, size_t max_descs) {{
            if (!ewts_id) return 0;
            size_t n = 0;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {{
                    if (out_descs && n < max_descs) {{
                        out_descs[n] = ewts_modules[i].description;
                    }}
                    ++n;
                }}
            }}
            return n;
        }}

        const char* ewts_first_key_from_module_id(const char* ewts_id) {{
            if (!ewts_id) return NULL;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {{
                    return ewts_modules[i].key;
                }}
            }}
            return NULL;
        }}

        const char* ewts_first_description_from_module_id(const char* ewts_id) {{
            if (!ewts_id) return NULL;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {{
                    return ewts_modules[i].description;
                }}
            }}
            return NULL;
        }}
    """)

    out_c = out_h.parents[2] / "src" / "ewts" / "module_keys.c"
    _write_text(out_h, content)
    _write_text(out_c, impl)


def _generate_c_log_levels(out_h: Path, *, levels_meta: dict) -> None:
    cases = "\n".join(
        [f'        case {v}: return "{k}";' for k, v in sorted(LEVELS.items(), key=lambda kv: kv[1])]
    )
    content = _c_block_banner(
        "C",
        generated_utc=GEN_UTC,
        levels_meta=levels_meta,
    ) + textwrap.dedent(f"""\
        #ifndef EWTS_LOG_LEVELS_H
        #define EWTS_LOG_LEVELS_H

        #ifdef __cplusplus
        extern "C" {{
        #endif

        static inline const char* ewts_log_level_name(int level) {{
            switch (level) {{
{cases}
                default: return "{DEFAULT_LEVEL_NAME}";
            }}
        }}

        #ifdef __cplusplus
        }}  // extern "C"
        #endif

        #endif  // EWTS_LOG_LEVELS_H
    """)
    _write_text(out_h, content)


def _generate_cpp_module_keys(modules: List[Module], out_hpp: Path, *, registry_meta: dict) -> None:
    entries = []
    for m in modules:
        desc = m.description.replace("\\", "\\\\").replace('"', '\\"')
        entries.append(f'    {{"{m.key}", "{m.ewts_id}", "{desc}"}}')
    entries_block = ",\n".join(entries)

    content = _c_block_banner(
        "C++",
        generated_utc=GEN_UTC,
        registry_meta=registry_meta,
    ) + textwrap.dedent(f"""\
        #ifndef EWTS_MODULE_KEYS_HPP
        #define EWTS_MODULE_KEYS_HPP

        #include <cstddef>
        #include <cstring>
        #include <vector>

        namespace ewts {{
        struct ModuleEntry {{
            const char* key;
            const char* ewts_id;
            const char* description;
        }};

        static const ModuleEntry kModules[] = {{
{entries_block}
        }};

        static const std::size_t kModulesCount = sizeof(kModules) / sizeof(kModules[0]);

        inline const char* EwtsIdFromKey(const char* key) {{
            if (!key) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].key, key) == 0) return kModules[i].ewts_id;
            }}
            return nullptr;
        }}

        inline const char* DescriptionFromKey(const char* key) {{
            if (!key) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].key, key) == 0) return kModules[i].description;
            }}
            return nullptr;
        }}

        inline std::vector<const char*> KeysFromEwtsId(const char* ewts_id) {{
            std::vector<const char*> out;
            if (!ewts_id) return out;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) out.push_back(kModules[i].key);
            }}
            return out;
        }}

        inline std::vector<const char*> DescriptionsFromEwtsId(const char* ewts_id) {{
            std::vector<const char*> out;
            if (!ewts_id) return out;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) out.push_back(kModules[i].description);
            }}
            return out;
        }}

        inline const char* FirstKeyFromEwtsId(const char* ewts_id) {{
            if (!ewts_id) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) return kModules[i].key;
            }}
            return nullptr;
        }}

        inline const char* FirstDescriptionFromEwtsId(const char* ewts_id) {{
            if (!ewts_id) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) return kModules[i].description;
            }}
            return nullptr;
        }}

        }}  // namespace ewts

        #endif  // EWTS_MODULE_KEYS_HPP
    """)
    _write_text(out_hpp, content)


def _generate_cpp_log_levels(out_hpp: Path, *, levels_meta: dict) -> None:
    cases = "\n".join(
        [f'    if (level == {v}) return "{k}";' for k, v in sorted(LEVELS.items(), key=lambda kv: kv[1])]
    )
    content = _c_block_banner(
        "C++",
        generated_utc=GEN_UTC,
        levels_meta=levels_meta,
    ) + textwrap.dedent(f"""\
        #ifndef EWTS_LOG_LEVELS_HPP
        #define EWTS_LOG_LEVELS_HPP

        namespace ewts {{
        inline const char* LogLevelName(int level) {{
{cases}
            return "{DEFAULT_LEVEL_NAME}";
        }}
        }}  // namespace ewts

        #endif  // EWTS_LOG_LEVELS_HPP
    """)
    _write_text(out_hpp, content)


def _generate_fortran_module_keys(modules: List[Module], out_f90: Path, *, registry_meta: dict) -> None:
    max_key = max(len(m.key) for m in modules)
    max_id = max(len(m.ewts_id) for m in modules)
    max_desc = max((len(m.description) for m in modules), default=0)
    max_key = max(max_key, 1)
    max_id = max(max_id, 1)
    max_desc = max(max_desc, 1)

    def _chunk(values: List[str], n: int) -> List[List[str]]:
        return [values[i:i+n] for i in range(0, len(values), n)]

    def _f_array(name: str, len_sym: str, values: List[str], *, per_line: int = 6) -> str:
        # Fortran 2003+ array constructor with explicit character(len=...) type-spec,
        # wrapped with continuation lines for readability.
        # Example:
        #   character(len=EWTS_KEY_LEN), parameter :: EWTS_KEYS(EWTS_MODULE_COUNT) = &
        #     [character(len=EWTS_KEY_LEN) :: &
        #       "a", "b", "c", &
        #       "d"
        #     ]
        lines: List[str] = []
        lines.append(f'          character(len={len_sym}), parameter :: {name}(EWTS_MODULE_COUNT) = &')
        lines.append(f'            [character(len={len_sym}) :: &')

        chunks = _chunk(values, per_line)
        for i, ch in enumerate(chunks):
            s = ", ".join(ch)
            # For continued statements, end each value line with '&'.
            # For all but last chunk, also include a trailing comma before '&'.
            if i != len(chunks) - 1:
                s += ", &"
            else:
                s += " &"
            lines.append(f"              {s}")
        lines.append("            ]")
        return "\n".join(lines) + "\n"

    keys_vals = [f'"{m.key}"' for m in modules]
    ids_vals = [f'"{m.ewts_id}"' for m in modules]
    desc_vals = [f'"{m.description.replace(chr(34), "")}"' for m in modules]  # strip quotes

    arrays_block = "\n".join([
        _f_array("EWTS_KEYS", "EWTS_KEY_LEN", keys_vals),
        _f_array("EWTS_IDS", "EWTS_ID_LEN", ids_vals),
        _f_array("EWTS_DESCS", "EWTS_DESC_LEN", desc_vals, per_line=1),  # descriptions are long; 1 per line
    ])

    content = _f_banner(
        generated_utc=GEN_UTC,
        registry_meta=registry_meta,
    ) + textwrap.dedent(f"""        module ewts_module_keys
          implicit none

          integer, parameter :: EWTS_MODULE_COUNT = {len(modules)}
          integer, parameter :: EWTS_KEY_LEN = {max_key}
          integer, parameter :: EWTS_ID_LEN = {max_id}
          integer, parameter :: EWTS_DESC_LEN = {max_desc}

{arrays_block}
        contains

          pure function ewts_id_from_key(key) result(ewts_id)
            character(len=*), intent(in) :: key
            character(len=EWTS_ID_LEN) :: ewts_id
            integer :: i
            ewts_id = ""
            do i = 1, EWTS_MODULE_COUNT
              if (trim(EWTS_KEYS(i)) == trim(key)) then
                ewts_id = EWTS_IDS(i)
                return
              end if
            end do
          end function ewts_id_from_key

          pure function ewts_description_from_key(key) result(desc)
            character(len=*), intent(in) :: key
            character(len=EWTS_DESC_LEN) :: desc
            integer :: i
            desc = ""
            do i = 1, EWTS_MODULE_COUNT
              if (trim(EWTS_KEYS(i)) == trim(key)) then
                desc = EWTS_DESCS(i)
                return
              end if
            end do
          end function ewts_description_from_key

          subroutine ewts_keys_from_id(ewts_id, out_keys, n)
            character(len=*), intent(in) :: ewts_id
            character(len=*), dimension(:), intent(out) :: out_keys
            integer, intent(out) :: n
            integer :: i, k
            n = 0
            k = 0
            do i = 1, EWTS_MODULE_COUNT
              if (trim(EWTS_IDS(i)) == trim(ewts_id)) then
                n = n + 1
                if (k < size(out_keys)) then
                  k = k + 1
                  out_keys(k) = trim(EWTS_KEYS(i))
                end if
              end if
            end do
          end subroutine ewts_keys_from_id

          subroutine ewts_descs_from_id(ewts_id, out_descs, n)
            character(len=*), intent(in) :: ewts_id
            character(len=*), dimension(:), intent(out) :: out_descs
            integer, intent(out) :: n
            integer :: i, k
            n = 0
            k = 0
            do i = 1, EWTS_MODULE_COUNT
              if (trim(EWTS_IDS(i)) == trim(ewts_id)) then
                n = n + 1
                if (k < size(out_descs)) then
                  k = k + 1
                  out_descs(k) = trim(EWTS_DESCS(i))
                end if
              end if
            end do
          end subroutine ewts_descs_from_id

        end module ewts_module_keys
    """)
    _write_text(out_f90, content)



def _generate_fortran_log_levels(out_f90: Path, *, levels_meta: dict) -> None:
    content = _f_banner(
        generated_utc=GEN_UTC,
        levels_meta=levels_meta,
    ) + textwrap.dedent("""\
        module ewts_log_levels
          implicit none
        contains
          pure function ewts_log_level_name(level) result(name)
            integer, intent(in) :: level
            character(len=16) :: name
            select case (level)
    """)
    for k, v in sorted(LEVELS.items(), key=lambda kv: kv[1]):
        content += f'            case ({v})\n              name = "{k}"\n'
    content += textwrap.dedent(f"""\
            case default
              name = "{DEFAULT_LEVEL_NAME}"
            end select
          end function ewts_log_level_name
        end module ewts_log_levels
    """)
    _write_text(out_f90, content)


def _generate_python_module_keys(modules: List[Module], out_py: Path, *, registry_meta: dict) -> None:
    key_to_id = {m.key: m.ewts_id for m in modules}
    key_to_desc = {m.key: m.description for m in modules}

    id_to_keys: Dict[str, List[str]] = {}
    id_to_descs: Dict[str, List[str]] = {}
    for m in modules:
        id_to_keys.setdefault(m.ewts_id, []).append(m.key)
        id_to_descs.setdefault(m.ewts_id, []).append(m.description)

    lines = [
        _py_banner(generated_utc=GEN_UTC, registry_meta=registry_meta),
        "from __future__ import annotations\n",
        "from typing import Dict, List, Optional\n\n",
        f"KEY_TO_EWTS_ID: Dict[str, str] = {key_to_id!r}\n",
        f"KEY_TO_DESCRIPTION: Dict[str, str] = {key_to_desc!r}\n",
        f"EWTS_ID_TO_KEYS: Dict[str, List[str]] = {id_to_keys!r}\n",
        f"EWTS_ID_TO_DESCRIPTIONS: Dict[str, List[str]] = {id_to_descs!r}\n\n",
        textwrap.dedent("""\
            def ewts_id_from_key(key: str) -> Optional[str]:
                \"\"\"Return EWTS module id for a key, or None if unknown.\"\"\"
                return KEY_TO_EWTS_ID.get(key)

            def description_from_key(key: str) -> Optional[str]:
                \"\"\"Return description for a key, or None if unknown.\"\"\"
                return KEY_TO_DESCRIPTION.get(key)

            def keys_from_ewts_id(ewts_id: str) -> List[str]:
                \"\"\"Return all keys that map to an EWTS id (duplicates supported).\"\"\"
                return list(EWTS_ID_TO_KEYS.get(ewts_id, []))

            def descriptions_from_ewts_id(ewts_id: str) -> List[str]:
                \"\"\"Return all descriptions for an EWTS id (duplicates supported).\"\"\"
                return list(EWTS_ID_TO_DESCRIPTIONS.get(ewts_id, []))

            def first_key_from_ewts_id(ewts_id: str) -> Optional[str]:
                \"\"\"Return the first key for an EWTS id in registry order, or None.\"\"\"
                keys = EWTS_ID_TO_KEYS.get(ewts_id)
                return keys[0] if keys else None

            def first_description_from_ewts_id(ewts_id: str) -> Optional[str]:
                \"\"\"Return the first description for an EWTS id in registry order, or None.\"\"\"
                descs = EWTS_ID_TO_DESCRIPTIONS.get(ewts_id)
                return descs[0] if descs else None
        """),
    ]
    _write_text(out_py, "".join(lines))



def _generate_c_payload_status(out_h: Path, *, payload_meta: dict) -> None:
    defines = "\n".join(
        [f'#define PAYLOAD_{name} "{value}"' for name, value in PAYLOAD_STATUSES.items()]
    )
    content = _c_block_banner(
        "C",
        generated_utc=GEN_UTC,
        payload_meta=payload_meta,
    ) + f"""#ifndef PAYLOAD_STATUS_H
#define PAYLOAD_STATUS_H

#ifdef __cplusplus
extern "C" {{
#endif

/* Payload status string constants used in EWTS status payload messages. */
{defines}

#ifdef __cplusplus
}}  // extern "C"
#endif

#endif  // PAYLOAD_STATUS_H
"""
    _write_text(out_h, content)


def _generate_cpp_payload_status(out_hpp: Path, *, payload_meta: dict) -> None:
    constants = "\n".join(
        [f'inline constexpr const char* PAYLOAD_{name} = "{value}";' for name, value in PAYLOAD_STATUSES.items()]
    )
    content = _c_block_banner(
        "C++",
        generated_utc=GEN_UTC,
        payload_meta=payload_meta,
    ) + f"""#ifndef PAYLOAD_STATUS_HPP
#define PAYLOAD_STATUS_HPP

namespace ewts {{

/* Payload status string constants used in EWTS status payload messages. */
{constants}

}}  // namespace ewts

#endif  // PAYLOAD_STATUS_HPP
"""
    _write_text(out_hpp, content)


def _generate_fortran_payload_status(out_f90: Path, *, payload_meta: dict) -> None:
    max_status_len = max((len(v) for v in PAYLOAD_STATUSES.values()), default=1)
    content = _f_banner(
        generated_utc=GEN_UTC,
        payload_meta=payload_meta,
    ) + f"""module ewts_payload_status
  implicit none

  integer, parameter :: PAYLOAD_STATUS_LEN = {max_status_len}

"""
    for name, value in PAYLOAD_STATUSES.items():
        content += f'  character(len=*), parameter :: PAYLOAD_{name} = "{value}"\n'
    content += "\nend module ewts_payload_status\n"
    _write_text(out_f90, content)


def _generate_python_log_levels(out_py: Path, *, levels_meta: dict) -> None:
    lines = [
        _py_banner(generated_utc=GEN_UTC, levels_meta=levels_meta),
        "from __future__ import annotations\n\n",
        f"LEVELS = {LEVELS!r}\n\n",
        textwrap.dedent(f"""\
            def log_level_name(level: int) -> str:
                for name, val in LEVELS.items():
                    if val == level:
                        return name
                return "{DEFAULT_LEVEL_NAME}"

            def parse_log_level(level: str | int | None, default: int = LEVELS["{DEFAULT_LEVEL_NAME}"]) -> int:
                \"\"\"
                Normalize a log level into an EWTS integer level.

                Accepts:
                  - int: returned as-is
                  - str: case-insensitive EWTS level name
                  - None: returns default

                NOTE:
                  - No aliases are supported.
                \"\"\"
                if level is None:
                    return default

                if isinstance(level, int):
                    return level

                if isinstance(level, str):
                    return LEVELS.get(level.strip().upper(), default)

                return default
        """),
    ]
    _write_text(out_py, "".join(lines))


# ----------------------- main -----------------------


def main() -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Generate EWTS language-specific include/source files from the "
            "specification files in the spec directory."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument(
        "--generate",
        default="all",
        choices=("all", "modules", "log-levels", "payload-status"),
        help=(
            "Select which group of files to generate. "
            "'all' generates modules, log levels, and payload status files; "
            "'modules' generates module keys/constants from the module registry; "
            "'log-levels' generates log-level files only; "
            "'payload-status' generates C, C++, and Fortran payload-status files only."
        ),
    )
    ap.add_argument(
        "--registry",
        default="spec/module_registry.yaml",
        help="Module registry specification, relative to the repository root.",
    )
    ap.add_argument(
        "--log-levels",
        default="spec/log_levels.json",
        help="Log-level specification, relative to the repository root.",
    )
    ap.add_argument(
        "--payload-status",
        default="spec/payload_status.json",
        help="Payload-status specification, relative to the repository root.",
    )
    ap.add_argument(
        "--only-payload-status",
        action="store_true",
        help=argparse.SUPPRESS,
    )
    ap.add_argument(
        "--repo-root",
        default=None,
        help=(
            "Repository root. If omitted, the repo root is inferred as the "
            "parent of the tools directory containing this script."
        ),
    )
    args = ap.parse_args()

    # Backward-compatible alias for the earlier one-off flag.
    if args.only_payload_status:
        args.generate = "payload-status"

    script_path = Path(__file__).resolve()
    repo_root = Path(args.repo_root).resolve() if args.repo_root else _infer_repo_root_from_script(script_path)

    registry_path = (repo_root / args.registry).resolve()
    log_levels_path = (repo_root / args.log_levels).resolve()
    payload_status_path = (repo_root / args.payload_status).resolve()

    generate_modules = args.generate in {"all", "modules"}
    generate_log_levels = args.generate in {"all", "log-levels"}
    generate_payload_status = args.generate in {"all", "payload-status"}

    rmeta = None
    lmeta = None
    pmeta = None
    modules: List[Module] = []
    c_modules: List[Module] = []
    cpp_modules: List[Module] = []
    fortran_modules: List[Module] = []
    python_modules: List[Module] = []

    if generate_modules:
        if not registry_path.exists():
            raise SystemExit(f"Registry file not found: {registry_path}")
        rmeta = _registry_meta(repo_root, registry_path)
        modules = _load_registry(registry_path)
        _validate_registry(modules)
        c_modules = _modules_for_language(modules, "c")
        cpp_modules = _modules_for_language(modules, "cpp")
        fortran_modules = _modules_for_language(modules, "fortran")
        python_modules = _modules_for_language(modules, "python")

    if generate_log_levels:
        if not log_levels_path.exists():
            raise SystemExit(f"Log-levels file not found: {log_levels_path}")
        lmeta = _load_log_levels(log_levels_path)
        lmeta["spec_path"] = _rel(repo_root, log_levels_path)

    if generate_payload_status:
        if not payload_status_path.exists():
            raise SystemExit(f"Payload-status file not found: {payload_status_path}")
        pmeta = _load_payload_statuses(payload_status_path)
        pmeta["spec_path"] = _rel(repo_root, payload_status_path)

    print("Using input specifications:")
    print(f"  - Generate target: {args.generate}")
    if rmeta:
        print(f"  - Module registry: {rmeta['spec_path']} (version: {rmeta['spec_version']})")
    if lmeta:
        print(f"  - Log levels spec: {lmeta['spec_path']} (version: {lmeta['spec_version']})")
    if pmeta:
        print(f"  - Payload status spec: {pmeta['spec_path']} (version: {pmeta['spec_version']})")
    print(f"  - Generation UTC:  {GEN_UTC}")
    print()

    # Outputs (match the documented layout)
    c_mod_h = repo_root / "runtime" / "c" / "include" / "ewts" / "module_keys.h"
    c_lvl_h = repo_root / "runtime" / "c" / "include" / "ewts" / "log_levels.h"
    c_payload_h = repo_root / "runtime" / "c" / "include" / "ewts" / "payload_status.h"

    cpp_mod_hpp = repo_root / "runtime" / "cpp" / "include" / "ewts" / "module_keys.hpp"
    cpp_lvl_hpp = repo_root / "runtime" / "cpp" / "include" / "ewts" / "log_levels.hpp"
    cpp_payload_hpp = repo_root / "runtime" / "cpp" / "include" / "ewts" / "payload_status.hpp"

    f_mod_f90 = repo_root / "runtime" / "fortran" / "src" / "ewts" / "module_keys.f90"
    f_lvl_f90 = repo_root / "runtime" / "fortran" / "src" / "ewts" / "log_levels.f90"
    f_payload_f90 = repo_root / "runtime" / "fortran" / "src" / "ewts" / "payload_status.f90"

    py_mod_py = repo_root / "runtime" / "python" / "ewts" / "src" / "ewts" / "module_keys.py"
    py_lvl_py = repo_root / "runtime" / "python" / "ewts" / "src" / "ewts" / "log_levels.py"

    # Optional convenience constants to avoid typos in module keys / ids
    c_const_h = repo_root / "runtime" / "c" / "include" / "ewts" / "module_constants.h"
    cpp_const_hpp = repo_root / "runtime" / "cpp" / "include" / "ewts" / "module_constants.hpp"
    f_const_f90 = repo_root / "runtime" / "fortran" / "src" / "ewts" / "module_constants.f90"
    py_const_py = repo_root / "runtime" / "python" / "ewts" / "src" / "ewts" / "modules.py"
    ngen_const_hpp = repo_root / "integrations" / "ngen" / "include" / "ewts_ngen" / "ngen_module_constants.hpp"
    ngen_keys_hpp = repo_root / "integrations" / "ngen" / "include" / "ewts_ngen" / "ngen_module_keys.hpp"

    if generate_modules:
        assert rmeta is not None
        _generate_c_module_keys(c_modules, c_mod_h, repo_root=repo_root, registry_meta=rmeta)
        _generate_cpp_module_keys(cpp_modules, cpp_mod_hpp, registry_meta=rmeta)
        _generate_fortran_module_keys(fortran_modules, f_mod_f90, registry_meta=rmeta)
        _generate_python_module_keys(python_modules, py_mod_py, registry_meta=rmeta)
        _generate_c_module_constants(c_modules, c_const_h, repo_root=repo_root, registry_meta=rmeta)
        _generate_cpp_module_constants(cpp_modules, cpp_const_hpp, registry_meta=rmeta)
        _generate_fortran_module_constants(fortran_modules, f_const_f90, registry_meta=rmeta)
        _generate_python_module_constants(python_modules, py_const_py, registry_meta=rmeta)
        _generate_ngen_module_constants(modules, ngen_const_hpp, registry_meta=rmeta)
        _generate_ngen_module_keys(modules, ngen_keys_hpp, registry_meta=rmeta)

    if generate_log_levels:
        assert lmeta is not None
        _generate_c_log_levels(c_lvl_h, levels_meta=lmeta)
        _generate_cpp_log_levels(cpp_lvl_hpp, levels_meta=lmeta)
        _generate_fortran_log_levels(f_lvl_f90, levels_meta=lmeta)
        _generate_python_log_levels(py_lvl_py, levels_meta=lmeta)

    if generate_payload_status:
        assert pmeta is not None
        _generate_c_payload_status(c_payload_h, payload_meta=pmeta)
        _generate_cpp_payload_status(cpp_payload_hpp, payload_meta=pmeta)
        _generate_fortran_payload_status(f_payload_f90, payload_meta=pmeta)

    print(f"Wrote EWTS generated files for target: {args.generate}.\n")
    print("Generated files:")
    for path in GENERATED_FILES:
        print(f"  - {_rel(repo_root, path)}")

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
