/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C++
 * Generated (UTC): 2026-06-18T18:13:15Z
 * Module registry: spec/module_registry.yaml
 * Module registry version: 1
 */
    #ifndef EWTS_NGEN_MODULE_KEYS_HPP
    #define EWTS_NGEN_MODULE_KEYS_HPP

    #include <cstddef>
    #include <cstring>
    #include <vector>

    namespace ewts_ngen {
    struct ModuleEntry {
        const char* key;
        const char* ewts_id;
        const char* description;
    };

    static const ModuleEntry kModules[] = {
{"ngen", "NGEN", "ngen framework"},
{"cfe-s", "CFE", "Conceptual Functional Equivalent to the National Water Model (Schaake)"},
{"cfe-x", "CFE", "Conceptual Functional Equivalent to the National Water Model (Xianjiang)"},
{"cfe", "CFE", "Conceptual Functional Equivalent to the National Water Model (Generic for logging)"},
{"forcing", "FORCING", "Forcing Engine"},
{"lasam", "LASAM", "Lumped Arid/Semi-arid Model"},
{"lstm", "LSTM", "Long Short-Term Memory Networks Model"},
{"noah-owp-modular", "NOAHOWP", "Noah OWP Land Surface Model"},
{"pet", "PET", "Potential Evapotranspiration Model"},
{"sac-sma", "SACSMA", "Sacramento Soil Moisture Accounting Model"},
{"sft", "SFT", "Soil Freeze-thaw Model"},
{"smp", "SMP", "Soil Moisture Profiles Model"},
{"snow-17", "SNOW17", "Snow Cccumulation and Melt Model"},
{"topmodel", "TOPMODEL", "Physically Based, Distributed Watershed Model"},
{"topoflow-glacier", "TFGLACR", "Glacier Model from the TopoFlow Model"},
{"t-route", "TROUTE", "T-Route routing"},
{"ueb", "UEB_BMI", "Utah Energy Balance Model"},
{"schism", "SCHISM", "Semi-implicit Cross-scale Hydroscience Integrated System Model (SCHISM)"},
{"sfincs", "SFINCS", "Super-fast modelling of dynamic compound flooding in Coastal Systems"},
{"msw-mgr", "MSWMGR", "Model Setup Workflow Component"},
{"cal-mgr", "CALMGR", "Calibration Manager Component"},
{"eval-mgr", "EVALMGR", "Evaluation Manager Component"},
{"fcst-mgr", "FCSTMGR", "Forecast Manager Component"},
{"rte", "RTE", "Runtime Environment Component"},
{"assim-engine", "ASSIM", "Assimilation Engine Component"}
    };

    static const std::size_t kModulesCount = sizeof(kModules) / sizeof(kModules[0]);

    inline const char* EwtsIdFromKey(const char* key) {
        if (!key) return nullptr;
        for (std::size_t i = 0; i < kModulesCount; ++i) {
            if (std::strcmp(kModules[i].key, key) == 0) return kModules[i].ewts_id;
        }
        return nullptr;
    }

    inline const char* DescriptionFromKey(const char* key) {
        if (!key) return nullptr;
        for (std::size_t i = 0; i < kModulesCount; ++i) {
            if (std::strcmp(kModules[i].key, key) == 0) return kModules[i].description;
        }
        return nullptr;
    }

    inline std::vector<const char*> KeysFromEwtsId(const char* ewts_id) {
        std::vector<const char*> out;
        if (!ewts_id) return out;
        for (std::size_t i = 0; i < kModulesCount; ++i) {
            if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) out.push_back(kModules[i].key);
        }
        return out;
    }

    inline std::vector<const char*> DescriptionsFromEwtsId(const char* ewts_id) {
        std::vector<const char*> out;
        if (!ewts_id) return out;
        for (std::size_t i = 0; i < kModulesCount; ++i) {
            if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) out.push_back(kModules[i].description);
        }
        return out;
    }

    inline const char* FirstKeyFromEwtsId(const char* ewts_id) {
        if (!ewts_id) return nullptr;
        for (std::size_t i = 0; i < kModulesCount; ++i) {
            if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) return kModules[i].key;
        }
        return nullptr;
    }

    inline const char* FirstDescriptionFromEwtsId(const char* ewts_id) {
        if (!ewts_id) return nullptr;
        for (std::size_t i = 0; i < kModulesCount; ++i) {
            if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) return kModules[i].description;
        }
        return nullptr;
    }

    }  // namespace ewts_ngen

    #endif  // EWTS_NGEN_MODULE_KEYS_HPP
