/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C++
 * Generated (UTC): 2026-06-18T18:13:15Z
 * Module registry: spec/module_registry.yaml
 * Module registry version: 1
 */

#ifndef EWTS_NGEN_MODULE_CONSTANTS_HPP
#define EWTS_NGEN_MODULE_CONSTANTS_HPP

namespace ewts_ngen {
namespace modules {

inline constexpr const char* EWTS_KEY_NGEN = "ngen";
inline constexpr const char* EWTS_ID_NGEN  = "NGEN";

inline constexpr const char* EWTS_KEY_CFE_S = "cfe-s";
inline constexpr const char* EWTS_ID_CFE_S  = "CFE";

inline constexpr const char* EWTS_KEY_CFE_X = "cfe-x";
inline constexpr const char* EWTS_ID_CFE_X  = "CFE";

inline constexpr const char* EWTS_KEY_CFE = "cfe";
inline constexpr const char* EWTS_ID_CFE  = "CFE";

inline constexpr const char* EWTS_KEY_FORCING = "forcing";
inline constexpr const char* EWTS_ID_FORCING  = "FORCING";

inline constexpr const char* EWTS_KEY_LASAM = "lasam";
inline constexpr const char* EWTS_ID_LASAM  = "LASAM";

inline constexpr const char* EWTS_KEY_LSTM = "lstm";
inline constexpr const char* EWTS_ID_LSTM  = "LSTM";

inline constexpr const char* EWTS_KEY_NOAH_OWP_MODULAR = "noah-owp-modular";
inline constexpr const char* EWTS_ID_NOAH_OWP_MODULAR  = "NOAHOWP";

inline constexpr const char* EWTS_KEY_PET = "pet";
inline constexpr const char* EWTS_ID_PET  = "PET";

inline constexpr const char* EWTS_KEY_SAC_SMA = "sac-sma";
inline constexpr const char* EWTS_ID_SAC_SMA  = "SACSMA";

inline constexpr const char* EWTS_KEY_SFT = "sft";
inline constexpr const char* EWTS_ID_SFT  = "SFT";

inline constexpr const char* EWTS_KEY_SMP = "smp";
inline constexpr const char* EWTS_ID_SMP  = "SMP";

inline constexpr const char* EWTS_KEY_SNOW_17 = "snow-17";
inline constexpr const char* EWTS_ID_SNOW_17  = "SNOW17";

inline constexpr const char* EWTS_KEY_TOPMODEL = "topmodel";
inline constexpr const char* EWTS_ID_TOPMODEL  = "TOPMODEL";

inline constexpr const char* EWTS_KEY_TOPOFLOW_GLACIER = "topoflow-glacier";
inline constexpr const char* EWTS_ID_TOPOFLOW_GLACIER  = "TFGLACR";

inline constexpr const char* EWTS_KEY_T_ROUTE = "t-route";
inline constexpr const char* EWTS_ID_T_ROUTE  = "TROUTE";

inline constexpr const char* EWTS_KEY_UEB = "ueb";
inline constexpr const char* EWTS_ID_UEB  = "UEB_BMI";

inline constexpr const char* EWTS_KEY_SCHISM = "schism";
inline constexpr const char* EWTS_ID_SCHISM  = "SCHISM";

inline constexpr const char* EWTS_KEY_SFINCS = "sfincs";
inline constexpr const char* EWTS_ID_SFINCS  = "SFINCS";

inline constexpr const char* EWTS_KEY_MSW_MGR = "msw-mgr";
inline constexpr const char* EWTS_ID_MSW_MGR  = "MSWMGR";

inline constexpr const char* EWTS_KEY_CAL_MGR = "cal-mgr";
inline constexpr const char* EWTS_ID_CAL_MGR  = "CALMGR";

inline constexpr const char* EWTS_KEY_EVAL_MGR = "eval-mgr";
inline constexpr const char* EWTS_ID_EVAL_MGR  = "EVALMGR";

inline constexpr const char* EWTS_KEY_FCST_MGR = "fcst-mgr";
inline constexpr const char* EWTS_ID_FCST_MGR  = "FCSTMGR";

inline constexpr const char* EWTS_KEY_RTE = "rte";
inline constexpr const char* EWTS_ID_RTE  = "RTE";

inline constexpr const char* EWTS_KEY_ASSIM_ENGINE = "assim-engine";
inline constexpr const char* EWTS_ID_ASSIM_ENGINE  = "ASSIM";

}  // namespace modules
}  // namespace ewts_ngen

#endif  // EWTS_NGEN_MODULE_CONSTANTS_HPP
